services:
  app:
    build:
      context: /var/jenkins_home/workspace/FUNYAMA/FunyamaProyect
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
        WWWUSER: '${WWWUSER:-1000}'
    container_name: funyama-app
    ports:
      - '${APP_PORT:-8081}:80'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      WWWGROUP: '${WWWGROUP:-1000}'
      DB_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - '.:/var/www/html'
    depends_on:
      - mysql
      - redis
    networks:
      - funyama-network

  mysql:
    image: 'mysql:8.0'
    container_name: funyama-mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
      MYSQL_USER: '${DB_USERNAME:-sail}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    networks:
      - funyama-network

  redis:
    image: 'redis:alpine'
    container_name: funyama-redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis-data:/data'
    networks:
      - funyama-network

networks:
  funyama-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
