pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/hernanmedina/FUNYAMA.git'
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker compose build'
            }
        }

        stage('Start Containers') {
            steps {
                sh 'docker compose up -d'
            }
        }

        stage('Run Migrations') {
            steps {
                //sh 'docker compose run --rm laravel.test php artisan migrate --force'
                sh 'docker compose exec -T laravel.test php artisan migrate --force'
            }
        }

        stage('Run Tests') {
            steps {
                //sh 'docker compose run --rm laravel.test php artisan test'
                sh 'docker compose exec -T laravel.test php artisan test'
            }
        }

        stage('Build Frontend') {
            steps {
                //sh 'docker compose run --rm laravel.test npm install'
                //sh 'docker compose run --rm laravel.test npm run build'
                sh 'docker compose exec -T laravel.test npm install'
                sh 'docker compose exec -T laravel.test npm run build'
            }
        }

        stage('Deploy') {
            steps {
               // Aquí el despliegue ocurre dentro del mismo contenedor de Laravel
                sh 'docker compose exec -T laravel.test php artisan config:cache'
                sh 'docker compose exec -T laravel.test php artisan route:cache'
                sh 'docker compose exec -T laravel.test php artisan view:cache'
            }
        }
    }

   
}
